### ISSUE TITLE
tutorial-complete branch is out of date/broken

### ISSUE THREAD

**Issue by ManAnRuck** [garden-io/web-app-example#1]
Hi just want to try out this example and recognised that the `tutorial-complete` branch is broken.

For example https://github.com/garden-io/web-app-example/blob/tutorial-complete/project.garden.yml#L27 is a broken configuration.
instead of:
```yaml
  - name: local
    defaultNamespace: ${var.userNamespace}
    # Setting the hostname as a variable so it can be referenced by actions
    hostname: local.app.garden
```
it should be
```yaml
  - name: local
    defaultNamespace: ${var.userNamespace}
    # Setting the hostname as a variable so it can be referenced by actions
    variables:
      hostname: local.app.gardenn
```
